---
- name: install docker and jenkins
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - docker
    - mountvolume
    - jenkins
  vars_files:
    - vars/aws.yml
    - vars/users.yml
