---
- name: create file system for attached volume
  filesystem:
        fstype: "{{ filetype }}"
        dev: "{{ device }}"

- name: create volume directory
  file:
        path: "{{ mount_path }}"
        state: directory

- name: mount volume
  mount:
        path: "{{ mount_path }}"
        src: "{{ device }}"
        fstype: "{{ filetype }}"
        state: mounted

- name: create docker volume
  file:
        path: /volumes/docker
        state: directory

- name: create symlink for to volume
  file:
        force: yes
        src: /volumes/docker
        path: /var/lib/docker
        state: link
