---
- name: create file system for attached volume
  filesystem:
        fstype: "{{ filetype }}"
        dev: "{{ device }}"

- name: create volume directory
  file:
        path: "{{ mount_path }}"
        state: directory

- name: mount volume
  mount:
        path: "{{ mount_path }}"
        src: "{{ device }}"
        fstype: "{{ filetype }}"
        state: mounted

